# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../data/v002/common", "/vagrant_data"

  config.vm.define "node01" do |node01|
#    config.vm.hostname "node01"
    config.vm.synced_folder "../data/v002/nodes/node01", "/vagrant_node_data"
    config.vm.network "private_network", ip: "192.168.88.10"
  end

  config.vm.define "node02" do |node02|
#    config.vm.hostname "node02"
    config.vm.synced_folder "../data/v002/nodes/node02", "/vagrant_node_data"
    config.vm.network "private_network", ip: "192.168.88.11"
  end


  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get -y upgrade
  #   apt-get install -y apache2
  SHELL
end
