# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "svenruppert/base_java8"

  config.vm.define "develop" do |node|
    config.vm.network "private_network", ip: "192.168.88.99"
  end

  config.vm.provision "shell", inline: <<-SHELL, privileged: false
     curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
     jabba install 1.9.0-146 
     jabba alias default 1.9.0-146
  SHELL
end
