# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define "base_linux" do |node|
    config.vm.network "private_network", ip: "192.168.88.1"
  end

  config.vm.provision "shell", inline: <<-SHELL, privileged: true
     apt-get update
     DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  SHELL
end
