# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "svenruppert/additional_apt"

  config.vm.define "base_java8" do |node|
    config.vm.network "private_network", ip: "192.168.88.3"
  end

  config.vm.provision "shell", inline: <<-SHELL, privileged: false
     curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
     jabba install 1.8 
     jabba alias default 1.8
  SHELL
end
