# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "svenruppert/base_linux"

  config.vm.define "additional_apt" do |node|
    config.vm.network "private_network", ip: "192.168.88.2"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL, privileged: true
     apt-get -y install curl
     apt-get -y install wget
  SHELL
end
