# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../data/v004/common", "/vagrant_data"

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      config.vm.synced_folder "../data/v004/nodes/node0#{i}", "/vagrant_node_data", create: true
      config.vm.network "private_network", ip: "192.168.88.#{i}"
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL, privileged: true
     apt-get update
     DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
     apt-get -y install curl
     apt-get -y install wget

     # wget http://apache.mirror.anlx.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
     # tar -zxf apache-maven-3.3.9-bin.tar.gz
     # cp -R apache-maven-3.3.9 /usr/local
     # ln -s /usr/local/apache-maven-3.3.9/bin/mvn /usr/bin/mvn
     # ln -s /usr/local/apache-maven-3.3.9/bin/mvnDebug /usr/bin/mvnDebug

  SHELL

  config.vm.provision "shell", inline: <<-SHELL, privileged: false
     curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
     jabba install 1.8 
     jabba alias default 1.8
  SHELL
end
