# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../data/v003/common", "/vagrant_data"

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      config.vm.synced_folder "../data/v003/nodes/node0#{i}", "/vagrant_node_data" , create:true
      config.vm.network "private_network", ip: "192.168.88.#{i}"
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get -y upgrade
  #   apt-get install -y apache2
  SHELL
end
